//! End to end coverage for rules, quoting, the cache and check

use larvae::config::Config;
use larvae::pipeline;
use larvae::rules::Family;
use std::fs;

mod common;
use common::*;

#[test]
fn quote_style_single_applies_everywhere() {
    let tmp = fixture();
    let root = tmp.path();

    write(
        root,
        "larvae.toml",
        "[aliases]\npkg = \"@game/ReplicatedStorage/Packages\"\n\n[process]\nquotes = \"single\"\n",
    );

    let config = Config::load_or_default(root).unwrap();
    let outcome = pipeline::run(root, &config, true).unwrap();

    for d in &outcome.diags {
        eprintln!("{d}");
    }

    assert!(!outcome.has_errors());

    // rewritten require uses single quotes
    let main = read(root, "dist/server/main.server.luau");
    assert!(
        main.contains("require('@game/ReplicatedStorage/Packages/signal')"),
        "{main}"
    );
    // untouched relative require gets requoted too
    let geometry = read(root, "dist/shared/util/geometry.luau");
    assert!(geometry.contains("require('./math')"), "{geometry}");
    // @self passthrough requoted
    let init = read(root, "dist/shared/pkg/init.luau");
    assert!(init.contains("require('@self/sub')"), "{init}");
}

#[test]
fn quote_style_threads_into_instance_exprs() {
    let tmp = instance_fixture("find_first_child");
    let root = tmp.path();

    write(
        root,
        "larvae.toml",
        concat!(
            "[aliases]\npkg = \"@game/ReplicatedStorage/Packages\"\n\n",
            "[process]\nquotes = \"single\"\n\n",
            "[requires]\ntarget = \"roblox-instance\"\n",
        ),
    );

    let config = Config::load_or_default(root).unwrap();
    let outcome = pipeline::run(root, &config, true).unwrap();

    assert!(!outcome.has_errors());
    let geometry = read(root, "dist/shared/util/geometry.luau");
    assert!(
        geometry.contains("require(script.Parent:FindFirstChild('math'))"),
        "{geometry}"
    );
}

#[test]
fn const_requires_rule() {
    let tmp = fixture();
    let root = tmp.path();

    write(
        root,
        "larvae.toml",
        "[aliases]\npkg = \"@game/ReplicatedStorage/Packages\"\n\n[rules]\nconst_requires = true\n",
    );

    let config = Config::load_or_default(root).unwrap();
    let outcome = pipeline::run(root, &config, true).unwrap();

    for d in &outcome.diags {
        eprintln!("{d}");
    }

    assert!(!outcome.has_errors());

    let main = read(root, "dist/server/main.server.luau");
    assert!(
        main.contains("const Signal = require(\"@game/ReplicatedStorage/Packages/signal\")"),
        "{main}"
    );
    assert!(
        main.contains("const math = require(\"@game/ReplicatedStorage/shared/util/math\")"),
        "{main}"
    );
    // non local requires untouched
    let consumer = read(root, "dist/shared/consumer.luau");
    assert!(consumer.contains("return require(\"./pkg\")"), "{consumer}");
}

#[test]
fn a_name_darklua_has_but_we_do_not_says_where_it_went() {
    let tmp = fixture();
    let root = tmp.path();

    // it is a real darklua name, it just is not a rule here
    write(root, "larvae.toml", "[rules]\nremove_spaces = true\n");
    let err = Config::load_or_default(root).unwrap_err().to_string();
    assert!(
        err.contains("remove_spaces") && err.contains("dense"),
        "{err}"
    );
}

#[test]
fn remove_comments_rule() {
    let tmp = fixture();
    let root = tmp.path();

    write(
        root,
        "larvae.toml",
        "[aliases]\npkg = \"@game/ReplicatedStorage/Packages\"\n\n[rules]\nremove_comments = true\n",
    );
    write(
        root,
        "src/shared/doc.luau",
        "--!strict\n-- a note\nlocal x = 1 -- trailing\nreturn x\n",
    );

    let config = Config::load_or_default(root).unwrap();
    let outcome = pipeline::run(root, &config, true).unwrap();

    assert!(!outcome.has_errors());

    let doc = read(root, "dist/shared/doc.luau");
    // Luau directives survive by default, plain comments do not
    assert!(doc.contains("--!strict"), "{doc}");
    assert!(!doc.contains("a note"), "{doc}");
    assert!(!doc.contains("trailing"), "{doc}");
    // line numbers preserved
    assert_eq!(doc.lines().count(), 4, "{doc}");
}

#[test]
fn append_text_comment_rule() {
    let tmp = fixture();
    let root = tmp.path();

    write(
        root,
        "larvae.toml",
        concat!(
            "[aliases]\npkg = \"@game/ReplicatedStorage/Packages\"\n\n",
            "[rules.append_text_comment]\ntext = \"generated by larvae\"\nlocation = \"start\"\n",
        ),
    );

    let config = Config::load_or_default(root).unwrap();
    let outcome = pipeline::run(root, &config, true).unwrap();

    assert!(!outcome.has_errors());
    let consumer = read(root, "dist/shared/consumer.luau");
    assert!(
        consumer.starts_with("-- generated by larvae\n"),
        "{consumer}"
    );
    assert!(consumer.contains("require(\"./pkg\")"), "{consumer}");
}

#[test]
fn darklua_rule_names_get_useful_errors() {
    let tmp = fixture();
    let root = tmp.path();

    let cases = [
        ("convert_require = true", "[requires]"),
        ("inject_global_value = true", "[defines]"),
        ("remove_spaces = true", "dense"),
    ];

    for (line, expect) in cases {
        write(root, "larvae.toml", &format!("[rules]\n{line}\n"));
        let err = Config::load_or_default(root).unwrap_err().to_string();
        assert!(err.contains(expect), "{line} -> {err}");
    }

    // a name darklua does not have either
    write(root, "larvae.toml", "[rules]\nmake_it_fast = true\n");
    let err = Config::load_or_default(root).unwrap_err().to_string();
    assert!(err.contains("unknown rule"), "{err}");
}

#[test]
fn cache_skips_unchanged_files_and_notices_edits() {
    let tmp = fixture();
    let root = tmp.path();
    let config = Config::load_or_default(root).unwrap();

    let first = pipeline::run(root, &config, true).unwrap();
    assert_eq!(first.stats.files_cached, 0, "cold build caches nothing");

    let second = pipeline::run(root, &config, true).unwrap();
    assert_eq!(
        second.stats.files_cached, second.stats.files_processed,
        "warm build should skip everything"
    );

    // editing one file rebuilds exactly that file
    write(
        root,
        "src/shared/util/geometry.luau",
        "local math = require(\"./math\")\nreturn { math }\n",
    );
    let third = pipeline::run(root, &config, true).unwrap();
    assert_eq!(
        third.stats.files_cached,
        third.stats.files_processed - 1,
        "only the edited file should rebuild"
    );
    assert!(read(root, "dist/shared/util/geometry.luau").contains("{ math }"));
}

#[test]
fn luaurc_change_invalidates_the_whole_cache() {
    let tmp = fixture();
    let root = tmp.path();
    let config = Config::load_or_default(root).unwrap();

    pipeline::run(root, &config, true).unwrap();
    let warm = pipeline::run(root, &config, true).unwrap();
    assert!(warm.stats.files_cached > 0);

    // a .luaurc changes how requires resolve for files that did not change
    write(root, ".luaurc", r#"{ "aliases": { "extra": "./src" } }"#);
    let after = pipeline::run(root, &config, true).unwrap();
    assert_eq!(
        after.stats.files_cached, 0,
        "resolution inputs changed, everything must rebuild"
    );
}

#[test]
fn deleting_a_source_removes_its_output() {
    let tmp = fixture();
    let root = tmp.path();
    let config = Config::load_or_default(root).unwrap();

    write(root, "src/shared/temporary.luau", "return 1\n");
    pipeline::run(root, &config, true).unwrap();
    assert!(root.join("dist/shared/temporary.luau").exists());

    fs::remove_file(root.join("src/shared/temporary.luau")).unwrap();
    let after = pipeline::run(root, &config, true).unwrap();
    assert!(
        !root.join("dist/shared/temporary.luau").exists(),
        "stale output should be pruned"
    );
    assert_eq!(after.stats.files_pruned, 1);
}

#[test]
fn check_reports_syntax_errors() {
    let tmp = fixture();
    let root = tmp.path();

    write(root, "src/shared/broken.luau", "local x = = 1\n");

    let config = Config::load_or_default(root).unwrap();
    let outcome = pipeline::run(root, &config, false).unwrap();

    assert!(outcome.has_errors());
    assert!(
        outcome
            .diags
            .iter()
            .any(|d| d.message.contains("syntax error")),
        "{:?}",
        outcome.diags.iter().map(|d| &d.message).collect::<Vec<_>>()
    );
}

#[test]
fn rules_that_touch_the_same_byte_do_not_corrupt_output() {
    // add_luau_directive inserts at byte 0 and const_requires replaces the
    // `local` that also starts at byte 0
    let tmp = fixture();
    let root = tmp.path();

    write(
        root,
        "larvae.toml",
        concat!(
            "[aliases]\npkg = \"@game/ReplicatedStorage/Packages\"\n\n",
            "[rules]\nconst_requires = true\nadd_luau_directive = \"strict\"\n",
        ),
    );
    write(
        root,
        "src/shared/first.luau",
        "local S = require(\"@pkg/signal\")\nreturn S\n",
    );

    let config = Config::load_or_default(root).unwrap();
    let outcome = pipeline::run(root, &config, true).unwrap();

    assert!(!outcome.has_errors());
    assert_eq!(
        read(root, "dist/shared/first.luau"),
        "--!strict\nconst S = require(\"@game/ReplicatedStorage/Packages/signal\")\nreturn S\n"
    );
}

#[test]
fn a_rule_that_loses_to_another_says_so() {
    let dir = fixture();
    let root = dir.path();

    /*
    group_local_assignment merges the two locals and rewrites that whole span,
    so compute_expression never gets to fold the sum inside it. The user asked
    for both rules and only got one, that has to be said out loud
    */
    write(
        root,
        "larvae.toml",
        concat!(
            "[aliases]\npkg = \"@game/ReplicatedStorage/Packages\"\n\n",
            "[rules]\ngroup_local_assignment = true\ncompute_expression = true\n",
        ),
    );
    write(
        root,
        "src/shared/pair.luau",
        "local a = 1\nlocal b = 2 + 3\nreturn a, b\n",
    );

    let cfg = Config::load_or_default(root).unwrap();
    let out = pipeline::run(root, &cfg, true).unwrap();

    let warned = out
        .diags
        .iter()
        .any(|d| d.message.contains("both rewrote these bytes"));

    assert!(warned, "expected a conflict warning, got {:?}", out.diags);
    assert!(!out.has_errors());
    // the winner still applied cleanly, a clash never mangles the output
    assert!(read(root, "dist/shared/pair.luau").contains("local a, b = 1, 2 + 3"));
}

#[test]
fn an_edit_inside_a_deletion_does_not_warn() {
    let dir = fixture();
    let root = dir.path();

    /*
    filter_after_early_return drops the unreachable statement that
    compute_expression wanted to fold inside, those bytes were leaving
    either way so there is nothing to report
    */
    write(
        root,
        "larvae.toml",
        concat!(
            "[aliases]\npkg = \"@game/ReplicatedStorage/Packages\"\n\n",
            "[rules]\nfilter_after_early_return = true\ncompute_expression = true\n",
        ),
    );
    write(
        root,
        "src/shared/dead.luau",
        "local function f()\n    do return 1 end\n    local x = 2 + 3\n    return x\nend\nreturn f\n",
    );

    let cfg = Config::load_or_default(root).unwrap();
    let out = pipeline::run(root, &cfg, true).unwrap();

    assert!(
        !out.diags
            .iter()
            .any(|d| d.message.contains("both rewrote these bytes")),
        "benign nesting should stay quiet, got {:?}",
        out.diags
    );
    assert!(!read(root, "dist/shared/dead.luau").contains("2 + 3"));
}

#[test]
fn the_summary_counts_rules_that_actually_did_something() {
    let tmp = fixture();
    let root = tmp.path();

    write(
        root,
        "larvae.toml",
        concat!(
            "[aliases]\npkg = \"@game/ReplicatedStorage/Packages\"\n\n",
            "[rules]\n",
            // two of ours and one parity rule that all fire
            "const_requires = true\nadd_luau_directive = \"strict\"\n",
            "compute_expression = true\n",
            // enabled but there is nothing in the source for it to do
            "remove_empty_do = true\n",
        ),
    );
    write(root, "src/shared/sum.luau", "local x = 2 + 3\nreturn x\n");

    let config = Config::load_or_default(root).unwrap();
    let outcome = pipeline::run(root, &config, true).unwrap();
    let s = &outcome.stats;

    assert!(!outcome.has_errors());
    // three fired, remove_empty_do had nothing to do so it is not counted
    assert_eq!(s.applied(Family::Native), 3, "{:?}", s.rules_applied);
    assert_eq!(s.applied(Family::Extension), 0);
}

/// A flag comment is an instruction to larvae, so by default it does not ship
#[test]
fn flag_comments_are_stripped_from_the_output() {
    let tmp = fixture();
    let root = tmp.path();

    write(
        root,
        "src/shared/flagged.luau",
        "-- larvae: allow(unused_variable)\nlocal unused = 1 -- a note\nreturn unused\n",
    );

    let config = Config::load_or_default(root).unwrap();
    let outcome = pipeline::run(root, &config, true).unwrap();

    assert!(!outcome.has_errors());

    let out = read(root, "dist/shared/flagged.luau");

    assert!(!out.contains("allow("), "the flag goes: {out}");
    assert!(
        out.contains("-- a note"),
        "an ordinary comment stays: {out}"
    );
    assert_eq!(out.lines().count(), 3, "line numbers hold: {out}");
}

#[test]
fn strip_flags_false_keeps_them() {
    let tmp = fixture();
    let root = tmp.path();

    write(
        root,
        "larvae.toml",
        "[aliases]\npkg = \"@game/ReplicatedStorage/Packages\"\n\n[process]\nstrip_flags = false\n",
    );
    write(
        root,
        "src/shared/flagged.luau",
        "-- larvae: allow(unused_variable)\nlocal unused = 1\nreturn unused\n",
    );

    let config = Config::load_or_default(root).unwrap();
    let outcome = pipeline::run(root, &config, true).unwrap();

    assert!(!outcome.has_errors());
    assert!(read(root, "dist/shared/flagged.luau").contains("allow(unused_variable)"));
}

/// remove_comments already speaks for every comment, so the two never both run
#[test]
fn remove_comments_wins_over_strip_flags() {
    let tmp = fixture();
    let root = tmp.path();

    write(
        root,
        "larvae.toml",
        "[aliases]\npkg = \"@game/ReplicatedStorage/Packages\"\n\n[rules]\nremove_comments = { except = [\"larvae:\"] }\n",
    );
    write(
        root,
        "src/shared/flagged.luau",
        "-- larvae: allow(unused_variable)\nlocal unused = 1 -- a note\nreturn unused\n",
    );

    let config = Config::load_or_default(root).unwrap();
    let outcome = pipeline::run(root, &config, true).unwrap();

    assert!(!outcome.has_errors());

    let out = read(root, "dist/shared/flagged.luau");

    assert!(
        out.contains("allow(unused_variable)"),
        "kept on purpose: {out}"
    );
    assert!(!out.contains("a note"), "and the rest still goes: {out}");
}
